In [1]:
import os
import time
import numpy as np

import pybullet as p
import pybullet_data
from surrol.utils.pybullet_utils import (
    step,
    get_joints,
    get_link_name,
    reset_camera,
)
from surrol.robots.ecm import Ecm

from surrol.const import ASSET_DIR_PATH

pybullet build time: Oct 15 2024 14:38:58


In [2]:
scaling = 1.

p.connect(p.GUI)
# p.connect(p.DIRECT)
p.setGravity(0, 0, -9.81)
p.setAdditionalSearchPath(pybullet_data.getDataPath())
reset_camera(yaw=10, pitch=-15, dist=0.9*scaling)

In [3]:
p.loadURDF("plane.urdf", [0, 0, -0.001], globalScaling=1)

# urdf_path = os.path.join(ASSET_DIR_PATH, 'ecm/ecm.urdf')
# urdf_path = os.path.join(ASSET_DIR_PATH, "ecm/ecm_dvrk.urdf")

# ecm = p.loadURDF(urdf_path, [0, 0, 0*scaling], 
#                  useFixedBase=True)

ecm = Ecm([0, 0, 0*scaling], 
          scaling=scaling)
ecm.reset_joint([0, 0, 0, 0])

[0, 0, 0, 0]

In [4]:
joints = get_joints(ecm.body)
print("There are {} joints.\n".format(len(joints)))

for i in range(0, len(joints)):
    print(get_link_name(ecm.body, i))

There are 11 joints.

ecm_yaw_link
ecm_pitch_end_link
ecm_main_insertion_link
ecm_tool_link
ecm_end_link
ecm_tip_link
ecm_pitch_front_link
ecm_pitch_bottom_link
ecm_pitch_top_link
ecm_pitch_back_link
ecm_remote_center_link


In [5]:
# continously run
p.setRealTimeSimulation(1)

while True:
    p.setGravity(0, 0, -9.81)
    time.sleep(0.01)

KeyboardInterrupt: 

## Forward Kinematics

In [6]:
ecm.reset_joint([0, 0, 0, 0])
joints = get_joints(ecm.body)

pose_rcm = ecm.get_current_position()
print(np.round(pose_rcm, 4))

[[ 1.e+00 -0.e+00 -0.e+00 -0.e+00]
 [-0.e+00 -1.e+00 -0.e+00  0.e+00]
 [-0.e+00  0.e+00 -1.e+00 -7.e-04]
 [ 0.e+00  0.e+00  0.e+00  1.e+00]]


In [7]:
ecm.reset_joint([-0.0024, -0.0023, 0.0025, -0.0007])

pose_rcm = ecm.get_current_position()
print(np.round(pose_rcm, 4))

# previously compute
# [[ 1.0000  0.0006 -0.0024 -0.0000]
#  [ 0.0007 -1.0000  0.0023  0.0000]
#  [-0.0024 -0.0023 -1.0000 -0.0032]
#  [ 0.0000  0.0000  0.0000  1.0000]]

[[ 1.0e+00  7.0e-04 -2.4e-03 -0.0e+00]
 [ 7.0e-04 -1.0e+00  2.3e-03  0.0e+00]
 [-2.4e-03 -2.3e-03 -1.0e+00 -3.2e-03]
 [ 0.0e+00  0.0e+00  0.0e+00  1.0e+00]]


In [9]:
ecm.reset_joint([0.0884, -0.6098, 0.1961, -0.0118])

pose_rcm = ecm.get_current_position()
print(np.round(pose_rcm, 4))

# [[ 0.9954  0.0623  0.0724  0.0142]
#  [ 0.0097 -0.8197  0.5727  0.1127]
#  [ 0.0950 -0.5694 -0.8166 -0.1607]
#  [ 0.0000  0.0000  0.0000  1.0000]]

[[ 0.9954  0.0623  0.0724  0.0142]
 [ 0.0097 -0.8197  0.5727  0.1127]
 [ 0.095  -0.5694 -0.8166 -0.1607]
 [ 0.      0.      0.      1.    ]]


In [10]:
ecm.reset_joint([0.5369, 0.1454, 0.0316, 0.1266])

pose_rcm = ecm.get_current_position()
print(np.round(pose_rcm, 4))

# [[ 0.8431 -0.1820  0.5060  0.0163]
#  [-0.1249 -0.9815  0.1449 -0.0047]
#  [ 0.5231  0.0590 -0.8502 -0.0275]
#  [ 0.0000  0.0000  0.0000  1.0000]]

[[ 0.8431 -0.182   0.5061  0.0163]
 [-0.1249 -0.9815 -0.1449 -0.0047]
 [ 0.5231  0.0589 -0.8502 -0.0275]
 [ 0.      0.      0.      1.    ]]


## Inverse Kinematics

In [11]:
pose_rcm = np.array([
    [ 1.,  0.,  0.,  0.],
    [ 0., -1.,  0.,  0.],
    [ 0.,  0., -1., -0.0007],
    [ 0.,  0.,  0.,  1.],
])

joints_inv = ecm.move(pose_rcm)
step(0.5)
print(np.round(joints_inv, 4))

# [0, 0, 0, 0]

[-0.  0.  0.  0.]


In [12]:
pose_rcm = np.array([
    [ 1.0000,  0.0006, -0.0024, -0.0000],
    [ 0.0007, -1.0000,  0.0023,  0.0000],
    [-0.0024, -0.0023, -1.0000, -0.0032],
    [ 0.0000,  0.0000,  0.0000,  1.0000],
])

joints_inv = ecm.move(pose_rcm)
step(0.5)
print(np.round(joints_inv, 4))

# [-0.0024, -0.0023, 0.0025, -0.0007]

[-0.0024 -0.0023  0.0025 -0.0007]


In [13]:
pose_rcm = np.array([
    [ 0.9954,  0.0623,  0.0724,  0.0142],
    [ 0.0097, -0.8197,  0.5727,  0.1127],
    [ 0.0950, -0.5694, -0.8166, -0.1607],
    [ 0.0000,  0.0000,  0.0000,  1.0000],
])

joints_inv = ecm.move(pose_rcm)
step(0.5)
print(np.round(joints_inv, 4))

# [0.0884, -0.6098, 0.1961, -0.0118]

[ 0.0884 -0.6098  0.1961 -0.0118]


In [14]:
pose_rcm = np.array([
    [ 0.8431, -0.182 ,  0.5061,  0.0163],
    [-0.1249, -0.9815, -0.1449, -0.0047],
    [ 0.5231,  0.0589, -0.8502, -0.0275],
    [ 0.    ,  0.    ,  0.    ,  1.    ],
])

joints_inv = ecm.move(pose_rcm)
step(0.5)
print(np.round(joints_inv, 4))

# [0.5369, 0.1454, 0.0316, 0.1266]

[0.5369 0.1454 0.0316 0.1266]


In [15]:
pose_rcm = np.array([
    [ 0.84306447, -0.18201039,  0.50607759,  0.01634631],
    [-0.12492979, -0.98152939, -0.14488822, -0.00467992],
    [ 0.52310119,  0.05892595, -0.85023107, -0.02746246],
    [ 0.        ,  0.        ,  0.        ,  1.        ],
])

joints_inv = ecm.move(pose_rcm)
step(0.5)
print(np.round(joints_inv, 4))

# [0.5369, 0.1454, 0.0316, 0.1266]

[0.5369 0.1454 0.0316 0.1266]
